### PR TITLE
ComfyGet PR

### PR DESCRIPTION
**Pull request by tbilik**
created pull request after first commit to comfyget, a fork of termget

### CODE REVIEW

**Comment by PizzaLovingNerd** [comment]
I feel like this is a separate project. Most of these features will be added soon. Also, if I commit these changes, TermGet has added lots of new features that would be removed because this pull request is old.

**Comment by tbilik** [comment]
Even if you want to keep the projects separate, please re-open so I can continue to merge TermGet code into ComfyGet. Thanks

**Comment by SadError256** [comment]
@tbilik You will need to move it into your own branch soon. This is completely seperate. This will be a stuck pull request if you don't pull it off.

**Comment by tbilik** [comment]
You can close it now.

**Pull request closed without merging**
